### PR TITLE
:bug: fix DateTime error

### LINKED ISSUE #177: [PE-D][Tester B] add_task, edit_task: 29, 30, 31 feb silently accepted as valid dates
sample commands:

`add_task n/foo dl/29-02-2022 1111` (not a leap year)

`add_task n/bar dl/30-02-2022 1111`

`add_task n/baz dl/31-02-2022 1111`

Expected: All of the above commands should reject the invalid non-leap year date.

Actual: Dates get added as 28-02-22.

Rationale:

While it's nice that leap years are recognized (on leap years they become 29/02), silent acceptance of these dates is a bug, especially because invalid dates are rejected (albeit w the wrong error message - separate issue):

`add_task n/pop dl/32-02-2022 1111`

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jontmy/ped#11

### LINKED ISSUE #180: [PE-D][Tester B] add_task: incorrect specificity for command error message on invalid dates
sample command: `add_task n/foo dl/32-12-2022 1111`

Expected: "invalid date" or equivalent

Actual: "Invalid command format"

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jontmy/ped#13

### PR DESCRIPTION
**Pull request by ShenyiCui**
## Description 
- Fixes the DateTime issue for silent failure of wrong dates
- Fixes message specificity for error message on dates

## Issues
- Resolves #180 
- Resolves #177

### CODE REVIEW

File: src/main/java/swift/logic/commands/AddTaskCommand.java [hunk 1]
```diff
@@ -64,6 +66,10 @@ public CommandResult execute(Model model) throws CommandException {
         if (model.hasTask(toAdd)) {
             throw new CommandException(MESSAGE_DUPLICATE_TASK);
         }
+        if (toAdd.getDeadline().map(x -> !Deadline.isValidDeadline(x.toString())).orElse(false)) {
+            System.out.println("Error Here");
```
Comment (yunruu) [inline src/main/java/swift/logic/commands/AddTaskCommand.java:70]: Do remove System.out.println() :)

File: src/main/java/swift/model/task/Deadline.java [hunk 2]
```diff
@@ -49,6 +50,7 @@ public int compareTo(Deadline other) {
 
     @Override
     public String toString() {
+        System.out.println(DATE_TIME_FORMATTER.format(deadline));
```
Comment (yunruu) [inline src/main/java/swift/model/task/Deadline.java:53]: Do remove this line :)

**Review by yunruu — CHANGES_REQUESTED** [review]
Hi! LGTM but some really minor changes to be made first 👍

File: src/main/java/swift/logic/commands/AddTaskCommand.java [hunk 3]
```diff
@@ -42,6 +43,7 @@ public class AddTaskCommand extends Command {
     public static final String MESSAGE_SUCCESS = "New task added: %1$s";
     public static final String MESSAGE_DUPLICATE_TASK = "This task already exists in the address book";
     public static final String MESSAGE_INVALID_CONTACT_INDEX = "The contact index provided is invalid";
+    public static final String MESSAGE_INVALID_DATE = "Deadline must valid and be in the `dd-MM-yyyy HHmm` format.";
```
Comment (yunruu) [inline src/main/java/swift/logic/commands/AddTaskCommand.java:46]: Small grammar mistake. Should be: "Deadline must be valid and in the `dd-MM-yyyy HHmm` format.";

**Review by yunruu — APPROVED** [review]
LGTM, thanks for the fix :)
