### PR TITLE
Fix: show all tasks and contacts after `list_contact` and `list_task`

### LINKED ISSUE #141: Bug: side panel lists do not show all tasks/contacts
Occurs when using any commands after calling a `select_task` or `select_contact` command

### PR DESCRIPTION
**Pull request by jasonqiu212**
## Issues
- Resolve #141

### CODE REVIEW

File: src/main/java/swift/logic/commands/ListTaskCommand.java [hunk 1]
```diff
@@ -27,14 +28,14 @@ public class ListTaskCommand extends Command {
     public CommandResult execute(Model model) {
         requireNonNull(model);
         model.updateFilteredTaskList(PREDICATE_SHOW_ALL_TASKS);
+        model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PEOPLE);
```
Comment (peppapighs) [inline src/main/java/swift/logic/commands/ListTaskCommand.java:31]: Add the expected behavior in UG.

File: src/main/java/swift/logic/commands/ListContactCommand.java [hunk 2]
```diff
@@ -23,6 +24,7 @@ public class ListContactCommand extends Command {
     public CommandResult execute(Model model) {
         requireNonNull(model);
         model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PEOPLE);
+        model.updateFilteredTaskList(PREDICATE_SHOW_ALL_TASKS);
```
Comment (peppapighs) [inline src/main/java/swift/logic/commands/ListContactCommand.java:27]: Add the expected behavior in UG.

**Review by ShenyiCui — APPROVED** [review]
LGTM
